Mangata dev v0.9.28
mangata-finance/polkadot pull request #13
Opened 2022-10-07 07:25 UTC by devdanco

2022-10-10 16:13 UTC, mateuszaaa approved these changes
looks like you forgot to remove some files

2022-10-10 16:15 UTC, mateuszaaa requested changes
looks like you forgot to remove some files, please compare branch state with proper tag in polkadot 


```
 ~/polkadot  mangata-dev-v0.9.28  git diff v0.9.28 --stat 
 Cargo.lock                                                            |  340 ++++++++---------
 bridges/.config/lingua.dic                                            |  243 ++++++++++++
 bridges/bin/millau/node/Cargo.toml                                    |   63 +++
 bridges/bin/millau/runtime/Cargo.toml                                 |  135 +++++++
 bridges/bin/millau/runtime/src/lib.rs                                 | 1002 ++++++++++++++++++++++++++++++++++++++++++++++++
 bridges/bin/rialto-parachain/node/Cargo.toml                          |   91 +++++
 bridges/bin/rialto-parachain/node/src/command.rs                      |  441 +++++++++++++++++++++


```

2022-10-10 18:08 UTC, devdanco commented
@mateuszaaa I forgot to push to repo. Resolved.

2022-10-12 08:12 UTC, iStrike7 approved these changes

2022-10-13 08:40 UTC, merged